defaults:
  # backends for this service
  backends: !env:json:secret:optional BACKENDS
  backendMap: !env:json:optional BACKEND_MAP

  # middleware intercepting requests
  middleware: !env:json:optional MIDDLEWARE

  # Taskcluster configuration
  taskcluster:
    rootUrl:                      !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:                   !env TASKCLUSTER_CLIENT_ID
      accessToken:                !env:secret TASKCLUSTER_ACCESS_TOKEN

  postgres:
    readDbUrl:                    !env:secret READ_DB_URL
    writeDbUrl:                   !env:secret WRITE_DB_URL
    dbCryptoKeys:                 !env:json:secret:optional DB_CRYPTO_KEYS

  monitoring:
    level:                        !env:optional LEVEL
    errorConfig:                  !env:json:secret:optional ERROR_CONFIG
    prometheusConfig:             !env:json:optional PROMETHEUS_CONFIG

  # Server configuration
  server:
    # Port to listen for requests on
    port:                           !env:number PORT

    # Environment 'development' or 'production'
    env:                            !env NODE_ENV
    # Force SSL, not useful when runnning locally
    forceSSL:                       !env:bool FORCE_SSL

    # Trust a forwarding proxy
    trustProxy:                     true

    # This is required to be larger than the downstream proxy timeout, default: 90s
    keepAliveTimeoutSeconds:        !env:number:optional KEEP_ALIVE_TIMEOUT_SECONDS

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:secret:optional NEW_RELIC
