defaults:
  # defaults outlining all configuration options and some sane defaults
  app:
    component: hooks
    scheduler:
      pollingDelay:   60000
  influx:
    connectionString: !env:secret:optional INFLUX_CONNECTION
    maxDelay:         300
    maxPendingPoints: 300
  azure:
    # deprecated way of specifying a crypto key
    cryptoKey:        !env:secret:optional AZURE_CRYPTO_KEY
  postgres:
    readDbUrl:        !env:secret READ_DB_URL
    writeDbUrl:       !env:secret WRITE_DB_URL
    dbCryptoKeys:     !env:json:secret:optional DB_CRYPTO_KEYS
  taskcluster:
    rootUrl:          !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env:secret TASKCLUSTER_ACCESS_TOKEN
  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:secret:optional ERROR_CONFIG
    prometheusConfig: !env:json:optional PROMETHEUS_CONFIG
  server:
    port:             !env:number PORT
    env:              !env NODE_ENV
    forceSSL:         !env:bool FORCE_SSL
    trustProxy:       !env:bool TRUST_PROXY
    # This is required to be larger than the downstream proxy timeout, default: 90s
    keepAliveTimeoutSeconds: !env:number:optional KEEP_ALIVE_TIMEOUT_SECONDS
  pulse:
    username:       !env:secret PULSE_USERNAME
    password:       !env:secret PULSE_PASSWORD
    hostname:       !env PULSE_HOSTNAME
    vhost:          !env PULSE_VHOST
    amqps:          !env:bool:optional PULSE_AMQPS
    # a list of regular expressions for exchanges that are prohibited
    denylist:
     # triggering a hook on task-created could create a "task bomb" that just spews
     # out tasks with no end, and isn't useful otherwise
     - exchange/taskcluster-queue/v1/task-created
     # changes to hooks themselves are internal and shouldn't trigger hooks
     - exchange/taskcluster-hooks/.*

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:secret:optional NEW_RELIC

test:
  # See user-config-example.yml for secrets credentials required for tests
  taskcluster:
    rootUrl: "https://tc.example.com"

  app:
    component:        hooks-tests
    scheduler:
      pollingDelay:   5000
  postgres:
    dbCryptoKeys:
      - id: 'hooks'
        algo: 'aes-256'
        key: "aSdtIGJzdGFjayEgaGVsbG8gZnV0dXJlIHBlcnNvbgo="
  azure:
    cryptoKey:        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
  server:
    port:             60401
    env:              development
    forceSSL:         false
    trustProxy:       false
  pulse:
    namespace:        'taskcluster-fake'
