---
defaults:
  app:
    jobQueue: 'jobs'
    deprecatedResultStatusQueue: 'stat-result'
    deprecatedInitialStatusQueue: 'stat-init'
    resultStatusQueue: 'ch-result'
    rerunQueue: 're-run'
    checkTaskRoute: 'checks'
    statusTaskRoute: 'statuses'
    statusContext: !env APPLICATION_NAME
    botName: !env BOT_USERNAME

  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    schedulerId: taskcluster-github
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env:secret TASKCLUSTER_ACCESS_TOKEN

  github:
    credentials:
      privatePEM: !env:secret GITHUB_PRIVATE_PEM
      appId: !env GITHUB_APP_ID

  webhook:
    secret: !env:list:secret WEBHOOK_SECRET

  intree:
    provisionerId: !env:optional PROVISIONER_ID
    workerType: !env:optional WORKER_TYPE

  postgres:
    readDbUrl: !env:secret READ_DB_URL
    writeDbUrl: !env:secret WRITE_DB_URL

  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:secret:optional ERROR_CONFIG
    prometheusConfig: !env:json:optional PROMETHEUS_CONFIG

  server:
    port: !env:number PORT
    env: !env NODE_ENV
    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY
    # This is required to be larger than the downstream proxy timeout, default: 90s
    keepAliveTimeoutSeconds: !env:number:optional KEEP_ALIVE_TIMEOUT_SECONDS

  pulse:
    hostname: !env PULSE_HOSTNAME
    username: !env:secret PULSE_USERNAME
    password: !env:secret PULSE_PASSWORD
    vhost: !env PULSE_VHOST
    amqps: !env:bool:optional PULSE_AMQPS
    namespace: taskcluster-github

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:secret:optional NEW_RELIC

test:
  app:
    botName: 'magicalTCspirit'
    jobQueue: 'test-jobs'
    deprecatedResultStatusQueue: 'deprecated-statuses'
    deprecatedInitialStatusQueue: 'deprecated-tasks'
    resultStatusQueue: 'checks-statuses'
    statusContext: 'Taskcluster-Test'

  github:
    credentials:
      appId: '66666'

  webhook:
    secret: ['abc123', 'def456']

  server:
    port: 60415
    env: development
    forceSSL: false
    trustProxy: false

  intree:
    provisionerId: 'dummy-provisioner'
    workerType: 'dummy-worker'

  taskcluster:
    schedulerId: tc-gh-devel
    rootUrl: "https://tc.example.com"

  pulse:
    namespace: 'taskcluster-fake'
    hostname: 'test-hostname'
    username: 'username'
    password: 'password'
    vhost: 'test-vhost'
