{{- if not (has "configmap" .Values.skipResourceTypes) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskcluster-secrets
  labels:
    app.kubernetes.io/name: taskcluster-secrets
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-secrets-secrets
    app.kubernetes.io/part-of: taskcluster
data:
  TASKCLUSTER_ROOT_URL: '{{ if typeIs "<nil>" .Values.rootUrl }}{{ else }}{{ if typeIs "string" .Values.rootUrl }}{{ .Values.rootUrl }}{{ else }}{{ .Values.rootUrl | toJson }}{{ end }}{{ end }}'
  TASKCLUSTER_CLIENT_ID: '{{ if typeIs "<nil>" .Values.secrets.taskcluster_client_id }}{{ else }}{{ if typeIs "string" .Values.secrets.taskcluster_client_id }}{{ .Values.secrets.taskcluster_client_id }}{{ else }}{{ .Values.secrets.taskcluster_client_id | toJson }}{{ end }}{{ end }}'
  LEVEL: '{{ if typeIs "<nil>" .Values.secrets.level }}{{ else }}{{ if typeIs "string" .Values.secrets.level }}{{ .Values.secrets.level }}{{ else }}{{ .Values.secrets.level | toJson }}{{ end }}{{ end }}'
  PROMETHEUS_CONFIG: '{{ if typeIs "<nil>" .Values.prometheus }}{{ else }}{{ if typeIs "string" .Values.prometheus }}{{ .Values.prometheus }}{{ else }}{{ .Values.prometheus | toJson }}{{ end }}{{ end }}'
  FORCE_SSL: '{{ if typeIs "<nil>" .Values.forceSSL }}{{ else }}{{ if typeIs "string" .Values.forceSSL }}{{ .Values.forceSSL }}{{ else }}{{ .Values.forceSSL | toJson }}{{ end }}{{ end }}'
  KEEP_ALIVE_TIMEOUT_SECONDS: '{{ if typeIs "<nil>" .Values.secrets.keep_alive_timeout_seconds }}{{ else }}{{ if typeIs "string" .Values.secrets.keep_alive_timeout_seconds }}{{ .Values.secrets.keep_alive_timeout_seconds }}{{ else }}{{ .Values.secrets.keep_alive_timeout_seconds | toJson }}{{ end }}{{ end }}'
  DEBUG: '{{ if typeIs "<nil>" .Values.secrets.debug }}{{ else }}{{ if typeIs "string" .Values.secrets.debug }}{{ .Values.secrets.debug }}{{ else }}{{ .Values.secrets.debug | toJson }}{{ end }}{{ end }}'
{{- end }}
