{{- if not (has "healthcheckpolicy" .Values.skipResourceTypes) -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: taskcluster-web-server-hc
  labels:
    app.kubernetes.io/name: taskcluster-web-server-hc
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-web-server-hc-healthcheckpolicy
    app.kubernetes.io/part-of: taskcluster
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /api/web-server/v1/ping
        port: 8080
  targetRef:
    group: ''
    kind: Service
    name: taskcluster-web-server
{{- end }}
